version: '3'
services:
    generated-api:
        container_name: generated-api
        build:
            context: ./
            dockerfile: Dockerfile
        image: generated_api:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/patientdb    
            - SPRING_DATASOURCE_USERNAME=dbuser
            - SPRING_DATASOURCE_PASSWORD=dbuser
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - 80:8080
        networks:
            - spring-cloud-network

    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=pgu                                    
            - POSTGRES_PASSWORD=pgp                           
        volumes:
        #   - "./database/init_mtdb.sql:/tmp/init_mtdb.sql"
          - "./database/mtdb:/var/lib/postgresql/data"
        ports:
            - 5431:5432




networks:
    spring-cloud-network:
        driver: bridge